export interface GraphNode {
  id: string
  name: string
  path: string
  size: number // lines of code
  dependencies: string[]
  dependents: string[]
  isTest: boolean
  type: 'component' | 'service' | 'util' | 'api' | 'hook'
}

export interface GraphEdge {
  source: string
  target: string
}

export const GRAPH_NODES: GraphNode[] = [
  {
    id: 'user-service',
    name: 'user.service.ts',
    path: 'src/services/user.service.ts',
    size: 342,
    dependencies: ['db-service', 'email-service', 'auth-utils'],
    dependents: ['user-api', 'admin-api', 'profile-component'],
    isTest: false,
    type: 'service',
  },
  {
    id: 'db-service',
    name: 'database.ts',
    path: 'src/services/database.ts',
    size: 521,
    dependencies: ['connection-pool', 'logger-util'],
    dependents: ['user-service', 'product-service', 'order-service'],
    isTest: false,
    type: 'service',
  },
  {
    id: 'email-service',
    name: 'email.service.ts',
    path: 'src/services/email.service.ts',
    size: 287,
    dependencies: ['logger-util', 'config-util'],
    dependents: ['user-service', 'order-service'],
    isTest: false,
    type: 'service',
  },
  {
    id: 'auth-utils',
    name: 'auth.utils.ts',
    path: 'src/utils/auth.utils.ts',
    size: 198,
    dependencies: ['crypto-util', 'jwt-lib'],
    dependents: ['user-service', 'middleware-auth'],
    isTest: false,
    type: 'util',
  },
  {
    id: 'user-api',
    name: '[id].ts',
    path: 'src/api/users/[id].ts',
    size: 256,
    dependencies: ['user-service', 'error-handler'],
    dependents: [],
    isTest: false,
    type: 'api',
  },
  {
    id: 'admin-api',
    name: 'admin.ts',
    path: 'src/api/admin.ts',
    size: 412,
    dependencies: ['user-service', 'product-service', 'auth-middleware'],
    dependents: [],
    isTest: false,
    type: 'api',
  },
  {
    id: 'profile-component',
    name: 'Profile.tsx',
    path: 'src/components/Profile.tsx',
    size: 289,
    dependencies: ['user-service', 'hooks-user', 'avatar-component'],
    dependents: [],
    isTest: false,
    type: 'component',
  },
  {
    id: 'connection-pool',
    name: 'connection-pool.ts',
    path: 'src/db/connection-pool.ts',
    size: 423,
    dependencies: ['logger-util'],
    dependents: ['db-service'],
    isTest: false,
    type: 'service',
  },
  {
    id: 'logger-util',
    name: 'logger.ts',
    path: 'src/utils/logger.ts',
    size: 167,
    dependencies: [],
    dependents: ['db-service', 'email-service', 'connection-pool'],
    isTest: false,
    type: 'util',
  },
  {
    id: 'config-util',
    name: 'config.ts',
    path: 'src/utils/config.ts',
    size: 89,
    dependencies: [],
    dependents: ['email-service'],
    isTest: false,
    type: 'util',
  },
  {
    id: 'product-service',
    name: 'product.service.ts',
    path: 'src/services/product.service.ts',
    size: 378,
    dependencies: ['db-service', 'cache-service'],
    dependents: ['product-api', 'admin-api'],
    isTest: false,
    type: 'service',
  },
  {
    id: 'product-api',
    name: '[id].ts',
    path: 'src/api/products/[id].ts',
    size: 234,
    dependencies: ['product-service', 'error-handler'],
    dependents: [],
    isTest: false,
    type: 'api',
  },
  {
    id: 'order-service',
    name: 'order.service.ts',
    path: 'src/services/order.service.ts',
    size: 456,
    dependencies: ['db-service', 'email-service', 'payment-service'],
    dependents: ['order-api', 'admin-api'],
    isTest: false,
    type: 'service',
  },
  {
    id: 'order-api',
    name: 'route.ts',
    path: 'src/api/orders/route.ts',
    size: 298,
    dependencies: ['order-service', 'error-handler'],
    dependents: [],
    isTest: false,
    type: 'api',
  },
  {
    id: 'cache-service',
    name: 'cache.service.ts',
    path: 'src/services/cache.service.ts',
    size: 312,
    dependencies: ['redis-lib'],
    dependents: ['product-service'],
    isTest: false,
    type: 'service',
  },
  {
    id: 'payment-service',
    name: 'payment.service.ts',
    path: 'src/services/payment.service.ts',
    size: 267,
    dependencies: ['stripe-lib', 'logger-util'],
    dependents: ['order-service'],
    isTest: false,
    type: 'service',
  },
  {
    id: 'middleware-auth',
    name: 'auth.middleware.ts',
    path: 'src/middleware/auth.middleware.ts',
    size: 143,
    dependencies: ['auth-utils', 'jwt-lib'],
    dependents: ['admin-api'],
    isTest: false,
    type: 'service',
  },
  {
    id: 'auth-middleware',
    name: 'auth.ts',
    path: 'src/middleware/auth.ts',
    size: 156,
    dependencies: ['auth-utils'],
    dependents: ['admin-api'],
    isTest: false,
    type: 'service',
  },
  {
    id: 'error-handler',
    name: 'error-handler.ts',
    path: 'src/utils/error-handler.ts',
    size: 134,
    dependencies: ['logger-util'],
    dependents: ['user-api', 'product-api', 'order-api'],
    isTest: false,
    type: 'util',
  },
  {
    id: 'hooks-user',
    name: 'useUser.ts',
    path: 'src/hooks/useUser.ts',
    size: 89,
    dependencies: ['user-service'],
    dependents: ['profile-component'],
    isTest: false,
    type: 'hook',
  },
  {
    id: 'avatar-component',
    name: 'Avatar.tsx',
    path: 'src/components/Avatar.tsx',
    size: 156,
    dependencies: [],
    dependents: ['profile-component'],
    isTest: false,
    type: 'component',
  },
  {
    id: 'crypto-util',
    name: 'crypto.ts',
    path: 'src/utils/crypto.ts',
    size: 201,
    dependencies: [],
    dependents: ['auth-utils'],
    isTest: false,
    type: 'util',
  },
  {
    id: 'jwt-lib',
    name: 'jwt.ts',
    path: 'src/lib/jwt.ts',
    size: 112,
    dependencies: [],
    dependents: ['auth-utils', 'middleware-auth'],
    isTest: false,
    type: 'util',
  },
  {
    id: 'redis-lib',
    name: 'redis.ts',
    path: 'src/lib/redis.ts',
    size: 234,
    dependencies: [],
    dependents: ['cache-service'],
    isTest: false,
    type: 'util',
  },
  {
    id: 'stripe-lib',
    name: 'stripe.ts',
    path: 'src/lib/stripe.ts',
    size: 187,
    dependencies: [],
    dependents: ['payment-service'],
    isTest: false,
    type: 'util',
  },
  {
    id: 'user-service-test',
    name: 'user.service.test.ts',
    path: 'src/services/__tests__/user.service.test.ts',
    size: 567,
    dependencies: ['user-service'],
    dependents: [],
    isTest: true,
    type: 'service',
  },
  {
    id: 'product-service-test',
    name: 'product.service.test.ts',
    path: 'src/services/__tests__/product.service.test.ts',
    size: 489,
    dependencies: ['product-service'],
    dependents: [],
    isTest: true,
    type: 'service',
  },
]

export const GRAPH_EDGES: GraphEdge[] = GRAPH_NODES.flatMap((node) =>
  node.dependencies.map((dep) => ({
    source: node.id,
    target: dep,
  }))
)
